#!/usr/bin/env python3
"""Build simplified article-level boolean flags from CAPES author-count CSV."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate simplified flags CSV with com_discentes/com_egressos/"
            "com_egressos_ou_discentes from article-level author-count CSV."
        )
    )
    parser.add_argument(
        "--in-csv",
        type=Path,
        required=True,
        help="Input CSV path generated by extract_artpe_autores_por_artigo.py.",
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        required=True,
        help="Output simplified CSV path.",
    )
    return parser.parse_args()


def to_int(value: object) -> int:
    text = str(value or "").strip()
    if not text:
        return 0
    text = text.replace(",", ".")
    try:
        return int(float(text))
    except ValueError:
        return 0


def as_bool_text(flag: bool) -> str:
    return "true" if flag else "false"


def build_output_row(row: Dict[str, str]) -> Dict[str, str]:
    qtd_discente = to_int(row.get("qtd_tp_autor_discente", "0"))
    qtd_egresso = to_int(row.get("qtd_tp_autor_egresso", "0"))

    com_discentes = qtd_discente > 0
    com_egressos = qtd_egresso > 0
    com_egressos_ou_discentes = com_discentes or com_egressos

    return {
        "id_add_producao_intelectual": str(row.get("id_add_producao_intelectual", "")).strip(),
        "an_base": str(row.get("an_base", "")).strip(),
        "cd_programa_ies": str(row.get("cd_programa_ies", "")).strip(),
        "nm_programa_ies": str(row.get("nm_programa_ies", "")).strip(),
        "com_discentes": as_bool_text(com_discentes),
        "com_egressos": as_bool_text(com_egressos),
        "com_egressos_ou_discentes": as_bool_text(com_egressos_ou_discentes),
    }


def main() -> int:
    args = parse_args()
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "id_add_producao_intelectual",
        "an_base",
        "cd_programa_ies",
        "nm_programa_ies",
        "com_discentes",
        "com_egressos",
        "com_egressos_ou_discentes",
    ]

    with args.in_csv.open("r", encoding="utf-8", newline="") as in_f, args.out_csv.open(
        "w", encoding="utf-8", newline=""
    ) as out_f:
        reader = csv.DictReader(in_f)
        writer = csv.DictWriter(out_f, fieldnames=fieldnames)
        writer.writeheader()

        count = 0
        for row in reader:
            writer.writerow(build_output_row(row))
            count += 1

    print(f"Input: {args.in_csv}")
    print(f"Output: {args.out_csv}")
    print(f"Rows written: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
